### PR TITLE
Change contact form email

### PR DESCRIPTION
**Pull request by adamhstewart**
Changes contact form email to sales@gizra.com.

@amitaibu mention me when/if committing, because I believe the form needs to be reactivated with formspree.

### CODE REVIEW

**Comment by amitaibu** [comment]
I'm unable to deploy from my laptop. Can you try and deploy?

`gulp publish && gulp deploy`

**Comment by amitaibu** [comment]
(and if you can't deploy, and until I fix it, you can edit the [index.html](https://github.com/shoov/shoov.io/blob/gh-pages/index.html) on the `gh-pages` directly.

**Comment by adamhstewart** [comment]
I don't have commit access to this repo - best I can do is a PR against the gh-pages branch - it doesn't seem that urgent.

either grant me commit access or deploy when you can.

**Comment by amitaibu** [comment]
I've added you before - you need to accept the invite (https://github.com/shoov/shoov.io/invitations)

**Comment by adamhstewart** [comment]
aha!

**Comment by adamhstewart** [comment]
deployed and tested.

**Pull request merged**
