### PR TITLE
Update index.html - fixing link to Shoov repo 

### PR DESCRIPTION
**Pull request by kazabooboo**
link is now pointing to https://github.com/shoov/shoov

### CODE REVIEW

**Comment by amitaibu** [comment]
Merged, but not deployed yet (having problem to deploy from my local - I'll re-try on Sunday)

**Comment by amitaibu** [comment]
Ok, fixed my local - deployed. And the bonus point is you getting a 👍 on your comment. (Very little cash value for that one, to be completely honest)

update_index_html_-_fixing_link_to_shoov_repo_by_kazabooboo_ _pull_request__43_ _shoov_shoov_io

**Comment by kazabooboo** [comment]
Meragesh -my first real commit.

Adar Earon,
gizra.com
Director, Gizra USA | 106 W32nd. St. 2nd Floor. New York, NY 10001 |
+1-347-686-4508

**Comment by amitaibu** [comment]
> my first real commit.

A first out of many..

**Pull request merged**
