### PR TITLE
Adding new content

### PR DESCRIPTION
**Pull request by YaronMiro**
#13

### CODE REVIEW

**Comment by amitaibu** [comment]
Thank. When you have something visual, please attach a screenshot.

**Comment by YaronMiro** [comment]
**Progress status image:**
selection_103

**Comment by YaronMiro** [comment]
**Progress:**
selection_107

**Comment by amitaibu** [comment]
:+1:

**Comment by YaronMiro** [comment]
**current design progress:**
Hi @niryariv
shoov io

**Comment by YaronMiro** [comment]
Hi @niryariv 
**Progress status:**
shoov io

**Comment by niryariv** [comment]
looks good

**Comment by YaronMiro** [comment]
@amitaibu, @niryariv 
**Progress status**

**Home page full**
shoov io

---

**Home mobile menu open**
main-menu mobile

---

**Glossary page full**
glossary shoov io

---

**Tutorial page full**
tutorial - shoov io-full

---

**Tutorial page lessons menu open**
selection_110

**Comment by niryariv** [comment]
@YaronMiro Gizra logo is all lowercase: "gizra"

**Comment by YaronMiro** [comment]
Merged manually.

**Pull request closed without merging**
