### PR TITLE
change form to contact instead of trial

### PR DESCRIPTION
**Pull request by niryariv**

### CODE REVIEW

**Comment by amitaibu** [comment]
Can you please check and deploy

**Comment by amitaibu** [comment]
@YaronMiro ^^

**Comment by YaronMiro** [comment]
@niryariv 
I see that the `website url` is no longer required is that on purpose ?

**Comment by amitaibu** [comment]
Please keep the URL required - it helps filter out spam

**Comment by YaronMiro** [comment]
OK I thought so... just wanted to check first. ^^
Thanks.

**Comment by YaronMiro** [comment]
Merged manually and deployed.

**Pull request closed without merging**
